In [1]:
%load_ext autoreload
%autoreload 2

import torch 
import torchvision
import sys
sys.path.append("../src")

In [2]:
from net import MNISTNetwork

config = dict()

mnist_net = MNISTNetwork(config)

inputs = torch.rand(16, 3, 28, 28)

out = mnist_net(inputs)

out

tensor([[0.0703, 0.0896, 0.0703, 0.0703, 0.0764, 0.0703, 0.0703, 0.0703, 0.2065,
         0.2058],
        [0.0951, 0.1047, 0.0954, 0.1033, 0.0951, 0.0983, 0.0951, 0.1010, 0.1169,
         0.0951],
        [0.0864, 0.0864, 0.1709, 0.0864, 0.0864, 0.0928, 0.0864, 0.1318, 0.0864,
         0.0864],
        [0.1087, 0.0940, 0.1315, 0.0940, 0.0996, 0.0963, 0.0940, 0.0940, 0.0940,
         0.0940],
        [0.0850, 0.0850, 0.1799, 0.0859, 0.0850, 0.0913, 0.0850, 0.1326, 0.0850,
         0.0850],
        [0.2364, 0.0615, 0.0565, 0.0565, 0.1053, 0.0565, 0.2248, 0.0565, 0.0565,
         0.0893],
        [0.0860, 0.0860, 0.1756, 0.0860, 0.0860, 0.0927, 0.0860, 0.1299, 0.0860,
         0.0860],
        [0.0876, 0.0876, 0.1800, 0.0876, 0.0876, 0.0943, 0.0876, 0.1126, 0.0876,
         0.0876],
        [0.0861, 0.0861, 0.1707, 0.0861, 0.0861, 0.0928, 0.0861, 0.1337, 0.0861,
         0.0861],
        [0.2723, 0.0541, 0.0541, 0.0541, 0.1191, 0.0541, 0.1476, 0.0541, 0.0541,
         0.1365],
        [0

In [18]:
a = torch.rand(3,4)

In [23]:
input1 = torch.randn(100, 128)

In [24]:
input2 = torch.randn(100, 128)

In [25]:
input1, input2

(tensor([[-0.6344,  0.3010, -0.8940,  ...,  0.4068, -0.4168, -1.7257],
         [ 0.5368, -1.1657, -1.0311,  ..., -0.5027,  0.7333, -0.1307],
         [ 0.2093,  1.3337, -1.3701,  ..., -0.7574,  1.7979,  0.0723],
         ...,
         [-1.5505,  1.7539,  0.6036,  ...,  0.4396, -0.7426, -0.3060],
         [-0.7444, -0.1038, -0.7774,  ..., -2.6107,  1.3335, -1.1474],
         [-0.5113, -0.7172, -2.3321,  ...,  1.2152,  0.8357, -1.4351]]),
 tensor([[ 0.9374, -1.3435,  0.5950,  ...,  0.5538,  1.8787,  1.5545],
         [ 0.4798, -1.1285, -1.8302,  ..., -0.7636, -1.3410,  1.1282],
         [-0.0301, -0.9640,  0.8616,  ...,  0.4630, -1.2327, -0.0357],
         ...,
         [-0.8278,  1.2640,  1.1891,  ...,  1.5675,  0.2623,  1.0484],
         [ 1.1806,  0.4437, -0.8227,  ..., -0.4222,  0.4586,  0.2119],
         [-0.0357,  1.9512, -0.0287,  ..., -0.5760,  1.7374, -0.0636]]))

In [41]:
input1.shape, input2.shape

(torch.Size([100, 128]), torch.Size([100, 128]))

In [39]:
output = torch.nn.functional.cosine_similarity(input1, input2,dim=1, eps=1e-6)

In [40]:
output.shape

torch.Size([100])

In [42]:
output[0]

tensor(-0.1205)

In [35]:
torch.where(output > 0, torch.tensor(1), torch.tensor(0))

tensor([0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
        1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
        1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
        0, 1, 1, 1])