In [1]:
import numpy as np

import keras

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [36]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [37]:
x_train = x_train.reshape(x_train.shape[0], 1, 28, 28)
x_test = x_test.reshape(x_test.shape[0], 1, 28, 28)

In [39]:
x_train = np.vstack((x_train, x_test))

In [50]:
y_true = np.hstack((y_train, y_test))

In [53]:
index = np.arange(60000)

In [56]:
x_train[index]

(60000, 1, 28, 28)

In [57]:
import keras.backend as K

In [62]:
K.eye(3,5)

<tf.Variable 'Variable_2:0' shape=(3, 3) dtype=int16_ref>

In [65]:
K.eval(K.eye(3,6))

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [80]:
import torch.nn as nn

In [87]:
a = nn.Linear(100,100)

In [88]:
list(a.parameters())

[Parameter containing:
 tensor([[-0.0661, -0.0631,  0.0965,  ..., -0.0054,  0.0320, -0.0963],
         [-0.0771,  0.0918, -0.0122,  ..., -0.0918, -0.0353,  0.0671],
         [-0.0059, -0.0925, -0.0285,  ...,  0.0768,  0.0218,  0.0010],
         ...,
         [-0.0023,  0.0171, -0.0833,  ...,  0.0004,  0.0294, -0.0884],
         [-0.0489,  0.0107, -0.0467,  ...,  0.0317, -0.0525, -0.0988],
         [ 0.0417,  0.0150,  0.0692,  ...,  0.0416,  0.0344, -0.0325]],
        requires_grad=True), Parameter containing:
 tensor([ 0.0937,  0.0193,  0.0844,  0.0314,  0.0737,  0.0992,  0.0176,  0.0091,
         -0.0488, -0.0232, -0.0443, -0.0589, -0.0732,  0.0004, -0.0835, -0.0544,
          0.0869,  0.0147,  0.0171,  0.0216, -0.0529,  0.0787,  0.0881,  0.0793,
         -0.0129, -0.0234,  0.0747, -0.0664,  0.0457, -0.0045, -0.0045, -0.0330,
          0.0823, -0.0578,  0.0682, -0.0365,  0.0934,  0.0838, -0.0150,  0.0947,
         -0.0308, -0.0885,  0.0901,  0.0620,  0.0909, -0.0248, -0.0576,  0.0759,

In [89]:
torch.nn.init.eye_(a.weight.data)

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 1., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [86]:
list(a.parameters())

[Parameter containing:
 tensor([[1., 0., 0.,  ..., 0., 0., 0.],
         [0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 1., 0., 0.],
         [0., 0., 0.,  ..., 0., 1., 0.],
         [0., 0., 0.,  ..., 0., 0., 1.]], requires_grad=True),
 Parameter containing:
 tensor([ 0.0331,  0.0196, -0.0203,  0.0835, -0.0137,  0.0423, -0.0448, -0.0445,
          0.0552, -0.0108,  0.0943,  0.0163,  0.0737,  0.0340,  0.0944,  0.0872,
          0.0902,  0.0682, -0.0929,  0.0020,  0.0466, -0.0678, -0.0847,  0.0978,
         -0.0559,  0.0640,  0.0960,  0.0839, -0.0763,  0.0233,  0.0085, -0.0759,
          0.0361,  0.0576,  0.0897,  0.0181,  0.0934, -0.0382,  0.0219, -0.0699,
         -0.0730, -0.0657, -0.0874,  0.0163, -0.0495, -0.0556, -0.0187,  0.0550,
         -0.0548,  0.0351, -0.0218, -0.0296,  0.0564,  0.0966,  0.0970, -0.0069,
         -0.0442,  0.0734, -0.0521, -0.0023,  0.0879, -0.0067, -0.0461,  0.0474,
         -0.0629,  0.085

In [1]:
import torch
import torchvision
import numpy as np
import torchvision.transforms as transforms
import sys
sys.path.append('../src')

In [4]:
def gen_mean_std(dataset1, dataset2, ratio=1):
    """sample 0.1
    """
    dataloader1 = torch.utils.data.DataLoader(dataset1, batch_size=int(len(dataset1)*ratio), shuffle=True, num_workers=10)
    train1 = iter(dataloader1).next()[0]
    dataloader2 = torch.utils.data.DataLoader(dataset2, batch_size=int(len(dataset2)*ratio), shuffle=True, num_workers=10)
    train2 = iter(dataloader2).next()[0]
    train = np.vstack((train1.numpy(), train2.numpy()))
    mean = np.mean(train, axis=(0,2,3))
    std = np.std(train, axis=(0,2,3))
    return mean, std

In [5]:
# mnist
train_dataset = torchvision.datasets.MNIST('../data', train=True, download=True, transform=transforms.Compose([transforms.ToTensor()]))
val_dataset = torchvision.datasets.MNIST('../data', train=False, download=True, transform=transforms.Compose([transforms.ToTensor()]))
mean, std = gen_mean_std(train_dataset, val_dataset)
print(mean, std)

[0.13092537] [0.30844885]


In [8]:
train_dataset.data.shape

torch.Size([60000, 28, 28])

In [9]:
train_dataset.targets.shape

torch.Size([60000])

In [10]:
a = np.array([1,2,3])

In [15]:
b = []

In [16]:
b.extend(a)

In [17]:
b

[1, 2, 3]

list